title: Harsh Gupta
description: My Portfolio of Data Science, Analytics, My Career, & Existential food for your soul.
author: Harsh Gupta
email: Harsh.Gupta5@utdallas.edu
phone: (214) 532-5542
github: https://github.com/harshbg
about: I am a Business Analytics student at <a href="https://www.utdallas.edu/" target="_blank"> UT Dallas</a> and a Data Science enthusiast.   I enjoy storytelling with statistics. 
disqus_shortname: DataJourneyman
google_analytics: UA-42822568-2
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/harshbg"
    - icon: fa-twitter
      link: "https://twitter.com/harshbg"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/harshbg/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/harshbg"

share:
  twitter_username: harshbg
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "http://gupta-harsh.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
