title: Harsh Gupta
description: Stuff that I come across and find interesting.
author: Harsh Gupta
email: hello@gupta-harsh.com
phone: (214) 532-5542
github: https://github.com/harshbg
about: I am a Business Analytics student at <a href="https://www.utdallas.edu/" target="_blank"> UT Dallas</a>. I enjoy storytelling with statistics and all things Data Science.
disqus_shortname: harshbg
google_analytics: UA-42822568-2
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/harshbg/"
    - icon: fa-github
      link: "https://github.com/harshbg"
    - icon: fa-facebook
      link: "https://www.facebook.com/harshbg"
    - icon: fa-twitter
      link: "https://twitter.com/harshbg"
    - icon: fa-book
      link: "https://www.goodreads.com/user/show/48393933-harsh-gupta"

share:
  twitter_username: harshbg
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: Tweets
      url: /tweets/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://harshbg.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
